//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldServer.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CfgCore : global::System.Configuration.ApplicationSettingsBase {
        
        private static CfgCore defaultInstance = ((CfgCore)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CfgCore())));
        
        public static CfgCore Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LogoutSeconds {
            get {
                return ((int)(this["LogoutSeconds"]));
            }
            set {
                this["LogoutSeconds"] = value;
            }
        }
    }
}
