//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldServer.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CfgDatabase : global::System.Configuration.ApplicationSettingsBase {
        
        private static CfgDatabase defaultInstance = ((CfgDatabase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CfgDatabase())));
        
        public static CfgDatabase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string LoginServerDaoHost {
            get {
                return ((string)(this["LoginServerDaoHost"]));
            }
            set {
                this["LoginServerDaoHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string LoginServerDaoUsername {
            get {
                return ((string)(this["LoginServerDaoUsername"]));
            }
            set {
                this["LoginServerDaoUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string LoginServerDaoPassword {
            get {
                return ((string)(this["LoginServerDaoPassword"]));
            }
            set {
                this["LoginServerDaoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bd_login")]
        public string LoginServerDaoDatabase {
            get {
                return ((string)(this["LoginServerDaoDatabase"]));
            }
            set {
                this["LoginServerDaoDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string GameServerDaoHost {
            get {
                return ((string)(this["GameServerDaoHost"]));
            }
            set {
                this["GameServerDaoHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string GameServerDaoUsername {
            get {
                return ((string)(this["GameServerDaoUsername"]));
            }
            set {
                this["GameServerDaoUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string GameServerDaoPassword {
            get {
                return ((string)(this["GameServerDaoPassword"]));
            }
            set {
                this["GameServerDaoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bd_world")]
        public string GameServerDaoDatabase {
            get {
                return ((string)(this["GameServerDaoDatabase"]));
            }
            set {
                this["GameServerDaoDatabase"] = value;
            }
        }
    }
}
